name: ios
on:
  workflow_dispatch:

# https://github.com/SomeRandomiOSDev/ProtocolProxy/blob/efd6de3f42b2927d7547591754fc9e30e026b4bd/.github/workflows/xcodebuild.yml
# https://github.com/SomeRandomiOSDev/ProtocolProxy
jobs:
  build:
    name: ${{ matrix.device }}
    runs-on: macos-11
    strategy:
      fail-fast: false
      matrix:
        include:
          - device: "iPhone 8"
          - device: "iPhone 8 Plus"
          - device: "iPhone 11"
          - device: "iPhone 11 Pro"
          - device: "iPhone 11 Pro Max"
          - device: "iPhone SE (2nd generation)"
          - device: "iPhone 12 mini"
          - device: "iPhone 12"
          - device: "iPhone 12 Pro"
          - device: "iPhone 12 Pro Max"
          - device: "iPhone 13 Pro"
          - device: "iPhone 13 Pro Max"
          - device: "iPhone 13 mini"
          - device: "iPhone 13"
          - device: "iPod touch (7th generation)"
          - device: "iPad Pro (9.7-inch)"
          - device: "iPad (7th generation)"
          - device: "iPad Pro (11-inch) (2nd generation)"
          - device: "iPad Pro (12.9-inch) (4th generation)"
          - device: "iPad Air (3rd generation)"
          - device: "iPad (8th generation)"
          - device: "iPad (9th generation)"
          - device: "iPad Air (4th generation)"
          - device: "iPad Pro (11-inch) (3rd generation)"
          - device: "iPad Pro (12.9-inch) (5th generation)"
          - device: "iPad mini (6th generation)"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install packages on MacOS
        run: |
          brew install tree || true
      - name: debug
        run: |
          xcrun simctl list devices available
          xcrun simctl list devices available | grep "iPhone [0-9]" | sort -rV | head -n 1 | sed -E 's/(.+)[ ]*\([^)]*\)[ ]*\([^)]*\)/\1/' | awk '{$1=$1};1'
      - name: Default scheme
        id: scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          echo "scheme_list $scheme_list"
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo "default $default"
          echo "::set-output name=default::${default}"
      - name: debug
        run: |
          tree .
      - name: Build iOS
        run: |
          xcodebuild -project "ProtocolProxy.xcodeproj" -scheme ${{ steps.scheme.outputs.default }} -destination "generic/platform=iOS" -configuration Debug SKIP_SWIFTLINT=YES
      - name: Build iOS Simulator
        run: |
          xcodebuild -project "ProtocolProxy.xcodeproj" -scheme ${{ steps.scheme.outputs.default }} -destination "generic/platform=iOS Simulator" -configuration Debug SKIP_SWIFTLINT=YES
      - name: debug
        run: |
          tree .
      - name: Test
        run: |
          # IOS_SIM="iPhone 12 Pro" # Fallback Simulator
          xcodebuild -project "ProtocolProxy.xcodeproj" -scheme ${{ steps.scheme.outputs.default }} -testPlan "ProtocolProxyTests" -destination "platform=iOS Simulator,name=${{ matrix.device }}" -configuration Debug SKIP_SWIFTLINT=YES ONLY_ACTIVE_ARCH=YES test
